

FROM node:20-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
COPY nginx.conf /etc/nginx/nginx.conf
RUN npm run build
FROM nginx:stable-alpine
COPY --from=builder nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]